seed: 42
verbose: False
data:
  networks: ["case30_ieee"]
  scenarios: [276000]
  normalization: "baseMVAnorm"
  baseMVA: 100
  mask_type: "rnd"
  mask_value: 0.0
  mask_ratio: 0.5
  mask_dim: 6
  learn_mask: False
  val_ratio: 0.1
  test_ratio: 0.1
  
model:
  type: "GPSTransformer"
  input_dim: 9
  output_dim: 6
  edge_dim: 2
  pe_dim: 20
  num_layers: 8
  hidden_size: 256
  attention_head: 8
  dropout: 0.1
  
training:
  batch_size: 32
  epochs: 200
  losses: ["GNSPBE", "MSE"]
  loss_weights: [1.0, 0.5]
  
optimizer:
  learning_rate: 0.0001
  beta1: 0.9
  beta2: 0.999
  lr_decay: 0.7
  lr_patience: 10
  
callbacks:
  patience: -1
  tol: 0